# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'session_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15session_service.proto\x12\x07session\"\x07\n\x05\x45mpty\"f\n\x14\x43reateSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x18\n\x10\x64uration_minutes\x18\x04 \x01(\x05\"\'\n\x11GetSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"q\n\x0fSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x18\n\x10\x64uration_minutes\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t2\xe2\x01\n\x0eSessionService\x12H\n\rCreateSession\x12\x1d.session.CreateSessionRequest\x1a\x18.session.SessionResponse\x12\x42\n\nGetSession\x12\x1a.session.GetSessionRequest\x1a\x18.session.SessionResponse\x12\x42\n\x14StreamActiveSessions\x12\x0e.session.Empty\x1a\x18.session.SessionResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_CREATESESSIONREQUEST']._serialized_start=43
  _globals['_CREATESESSIONREQUEST']._serialized_end=145
  _globals['_GETSESSIONREQUEST']._serialized_start=147
  _globals['_GETSESSIONREQUEST']._serialized_end=186
  _globals['_SESSIONRESPONSE']._serialized_start=188
  _globals['_SESSIONRESPONSE']._serialized_end=301
  _globals['_SESSIONSERVICE']._serialized_start=304
  _globals['_SESSIONSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
